# Install Packages
install.packages("tidyverse")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("DESeq2")
BiocManager::install("vsn")
install.packages("pheatmap")
install.packages("ggridges")
BiocManager::install("clusterProfiler")
BiocManager::install("pathview")
BiocManager::install("enrichplot")
install.packages("GSEABase")
install.packages("ggnewscale")
install.packages("fgsea")
install.packages("DOSE")
install.packages("msigdbr")
BiocManager::install("biomaRt")
BiocManager::install("GSEABase")
install.packages("wordcloud")
install.packages('xlsx')
install.packages("forcats")
install.packages("survminer")
BiocManager::install("TCGAbiolinks")
BiocManager::install('EnhancedVolcano')
install.packages("ggupset")
BiocManager::install("ReactomePA")



# Load libraries
library(readr)
library(org.Hs.eg.db)
library(vsn)
library(DESeq2)
library(pheatmap)
library(ggplot2)
library(dplyr)
library(stringr)
library(reshape2)
library(clusterProfiler)
library(enrichplot)
library(GSEABase)
library(fgsea)
library(ggnewscale)
library(DOSE)
library(msigdbr)
library(biomaRt)
library(pathview)
library(ggridges)
library(wordcloud)
library(xlsx)
library(forcats)
library(survival)
library(SummarizedExperiment)
library(survminer)
library(TCGAbiolinks)
library(EnhancedVolcano)
library(hrbrthemes)
library(ggupset)
library(ReactomePA)



sessionInfo()